const KEY='shelterSudanData';
const demo={shelters:[{id:1,name:'Al Amal Shelter',location:'Khartoum',capacity:180,occupied:126},{id:2,name:'Peace Community Center',location:'Gedaref',capacity:240,occupied:168},{id:3,name:'Unity School Shelter',location:'White Nile',capacity:120,occupied:120}],families:[{id:1,name:'Ahmed Family',members:6,shelter:'Al Amal Shelter',needs:'Food, water',date:'2026-09-15'},{id:2,name:'Hassan Family',members:4,shelter:'Peace Community Center',needs:'Medicine',date:'2026-09-16'}],aid:[{id:1,beneficiary:'Ahmed Family',type:'Food',qty:'20 kits',provider:'Relief Team',date:'2026-09-17'},{id:2,beneficiary:'Hassan Family',type:'Medicine',qty:'12 packs',provider:'Health Partner',date:'2026-09-18'}]};
function data(){try{return JSON.parse(localStorage.getItem(KEY))||demo}catch(e){return demo}}
function save(d){localStorage.setItem(KEY,JSON.stringify(d))}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function login(e){e.preventDefault();const em=document.getElementById('email').value.trim(),pw=document.getElementById('password').value;const err=document.getElementById('loginError');if(em==='admin@shelter.com'&&pw==='123456'){localStorage.setItem('shelterLoggedIn','1');location.href='dashboard.html'}else err.textContent='Incorrect email or password.'}
function guard(){if(!localStorage.getItem('shelterLoggedIn'))location.href='index.html'}
function logout(){localStorage.removeItem('shelterLoggedIn');location.href='index.html'}
function openModal(id){document.getElementById(id)?.classList.add('show')};function closeModal(id){document.getElementById(id)?.classList.remove('show')}
function status(s){const p=s.capacity?Math.round(s.occupied/s.capacity*100):0;if(p>=100)return ['Full','full'];if(p>=70)return ['Limited','limited'];return ['Available','available']}
function renderShelters(){const el=document.getElementById('shelterTable');if(!el)return;guard();const q=(document.getElementById('shelterSearch')?.value||'').toLowerCase();const d=data();const rows=d.shelters.filter(s=>(s.name+' '+s.location).toLowerCase().includes(q));el.innerHTML=rows.map(s=>{const st=status(s);return `<tr><td><b>${esc(s.name)}</b></td><td>${esc(s.location)}</td><td>${s.capacity}</td><td>${s.occupied}</td><td><span class="badge ${st[1]}">${st[0]}</span></td><td><button class="delete" onclick="removeItem('shelters',${s.id})">Delete</button></td></tr>`}).join('')||'<tr><td colspan="6" class="muted">No shelters found.</td></tr>'}
function addShelter(e){e.preventDefault();const d=data();d.shelters.push({id:Date.now(),name:document.getElementById('sName').value,location:document.getElementById('sLocation').value,capacity:+document.getElementById('sCapacity').value,occupied:+document.getElementById('sOccupied').value});save(d);closeModal('shelterModal');e.target.reset();renderShelters()}
function renderFamilies(){const el=document.getElementById('familyTable');if(!el)return;guard();const q=(document.getElementById('familySearch')?.value||'').toLowerCase();const d=data();const rows=d.families.filter(f=>(f.name+' '+f.shelter+' '+f.needs).toLowerCase().includes(q));el.innerHTML=rows.map(f=>`<tr><td><b>${esc(f.name)}</b></td><td>${f.members}</td><td>${esc(f.shelter)}</td><td>${esc(f.needs)}</td><td>${esc(f.date)}</td><td><button class="delete" onclick="removeItem('families',${f.id})">Delete</button></td></tr>`).join('')||'<tr><td colspan="6" class="muted">No families found.</td></tr>'}
function populateShelterOptions(){const s=document.getElementById('fShelter');if(!s)return;s.innerHTML=data().shelters.map(x=>`<option>${esc(x.name)}</option>`).join('')||'<option value="">No shelters</option>'}
function addFamily(e){e.preventDefault();const d=data();d.families.push({id:Date.now(),name:document.getElementById('fName').value,members:+document.getElementById('fMembers').value,shelter:document.getElementById('fShelter').value,needs:document.getElementById('fNeeds').value,date:new Date().toISOString().slice(0,10)});save(d);closeModal('familyModal');e.target.reset();renderFamilies()}
function renderAid(){const el=document.getElementById('aidTable');if(!el)return;guard();const q=(document.getElementById('aidSearch')?.value||'').toLowerCase();const d=data();const rows=d.aid.filter(a=>(a.beneficiary+' '+a.type+' '+a.provider).toLowerCase().includes(q));el.innerHTML=rows.map(a=>`<tr><td><b>${esc(a.beneficiary)}</b></td><td>${esc(a.type)}</td><td>${esc(a.qty)}</td><td>${esc(a.provider)}</td><td>${esc(a.date)}</td><td><button class="delete" onclick="removeItem('aid',${a.id})">Delete</button></td></tr>`).join('')||'<tr><td colspan="6" class="muted">No assistance records found.</td></tr>'}
function populateFamilyOptions(){const s=document.getElementById('aFamily');if(!s)return;s.innerHTML=data().families.map(x=>`<option>${esc(x.name)}</option>`).join('')||'<option value="">No families</option>';document.getElementById('aDate').value=new Date().toISOString().slice(0,10)}
function addAid(e){e.preventDefault();const d=data();d.aid.push({id:Date.now(),beneficiary:document.getElementById('aFamily').value,type:document.getElementById('aType').value,qty:document.getElementById('aQty').value,provider:document.getElementById('aProvider').value,date:document.getElementById('aDate').value});save(d);closeModal('aidModal');e.target.reset();renderAid()}
function removeItem(type,id){const d=data();d[type]=d[type].filter(x=>x.id!==id);save(d);renderShelters();renderFamilies();renderAid();refreshDashboard()}
function seedDemo(){localStorage.setItem(KEY,JSON.stringify(demo));renderShelters();renderFamilies();renderAid();refreshDashboard()}
function refreshDashboard(){const d=data();const sh=document.getElementById('statShelters');if(!sh)return;document.getElementById('statShelters').textContent=d.shelters.length;document.getElementById('statFamilies').textContent=d.families.length;document.getElementById('statCapacity').textContent=d.shelters.reduce((a,s)=>a+Math.max(0,s.capacity-s.occupied),0);document.getElementById('statAid').textContent=d.aid.length;document.getElementById('occupancyList').innerHTML=d.shelters.map(s=>{const p=s.capacity?Math.min(100,Math.round(s.occupied/s.capacity*100)):0;return `<div class="occ-row"><span>${esc(s.name)}</span><div class="bar"><i style="width:${p}%"></i></div><b>${p}%</b></div>`}).join('')||'<p class="muted">No shelters registered yet.</p>';document.getElementById('recentAid').innerHTML=d.aid.slice(-5).reverse().map(a=>`<tr><td>${esc(a.beneficiary)}</td><td>${esc(a.type)}</td><td>${esc(a.qty)}</td><td>${esc(a.date)}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">No assistance recorded yet.</td></tr>'}
function refreshReports(){const d=data();if(!document.getElementById('rOccupancy'))return;const cap=d.shelters.reduce((a,s)=>a+s.capacity,0),occ=d.shelters.reduce((a,s)=>a+s.occupied,0);document.getElementById('rOccupancy').textContent=(cap?Math.round(occ/cap*100):0)+'%';document.getElementById('rMembers').textContent=d.families.reduce((a,f)=>a+f.members,0);document.getElementById('rCapacity').textContent=d.shelters.reduce((a,s)=>a+Math.max(0,s.capacity-s.occupied),0);document.getElementById('rAid').textContent=d.aid.length;document.getElementById('reportBars').innerHTML=d.shelters.map(s=>{const p=s.capacity?Math.min(100,Math.round(s.occupied/s.capacity*100)):0;return `<div class="bar-line"><span>${esc(s.name)}</span><div class="bar"><i style="width:${p}%"></i></div><b>${p}%</b></div>`}).join('')||'<p class="muted">No shelter data available.</p>'}
document.addEventListener('DOMContentLoaded',()=>{if(document.getElementById('loginForm'))document.getElementById('loginForm').addEventListener('submit',login);if(document.querySelector('.app'))guard();renderShelters();renderFamilies();renderAid();refreshDashboard();refreshReports()});
