const KEY='shelterPlatformData';
const DEFAULT={shelters:[{id:1,name:'Al Aman Shelter',location:'Khartoum',capacity:500,occupancy:420},{id:2,name:'Al Salam Shelter',location:'Omdurman',capacity:300,occupancy:280}],families:[{id:1,head:'Ahmed Mohamed',members:5,shelter:'Al Aman Shelter',phone:'',needs:'Food and clothing'},{id:2,head:'Fatima Ali',members:4,shelter:'Al Salam Shelter',phone:'',needs:'Medicine'}],assistance:[{id:1,beneficiary:'Ahmed Mohamed Family',type:'Food',details:'Food package',date:'22 Aug 2026',status:'Delivered'}]};
function getData(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(DEFAULT)}catch{return structuredClone(DEFAULT)}}
function saveData(d){localStorage.setItem(KEY,JSON.stringify(d))}
function login(e){e.preventDefault();localStorage.setItem('loggedIn','1');location.href='dashboard.html'}
function logout(){localStorage.removeItem('loggedIn');location.href='index.html'}
function guard(){if(!localStorage.getItem('loggedIn'))location.href='index.html'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toast(m){const a=document.getElementById('alert');if(a){a.textContent=m;a.style.display='block';setTimeout(()=>a.style.display='none',2200)}}
function addShelter(e){e.preventDefault();const f=e.target,d=getData();d.shelters.push({id:Date.now(),name:f.name.value,location:f.location.value,capacity:+f.capacity.value,occupancy:+f.occupancy.value});saveData(d);f.reset();toast('Shelter added successfully.');renderShelters();renderDashboard()}
function deleteShelter(id){const d=getData();d.shelters=d.shelters.filter(x=>x.id!==id);saveData(d);renderShelters();renderDashboard()}
function addFamily(e){e.preventDefault();const f=e.target,d=getData();d.families.push({id:Date.now(),head:f.head.value,members:+f.members.value,shelter:f.shelter.value,phone:f.phone.value,needs:f.needs.value});saveData(d);f.reset();toast('Family registered successfully.');renderFamilies();renderDashboard()}
function deleteFamily(id){const d=getData();d.families=d.families.filter(x=>x.id!==id);saveData(d);renderFamilies();renderDashboard()}
function addAssistance(e){e.preventDefault();const f=e.target,d=getData();d.assistance.unshift({id:Date.now(),beneficiary:f.beneficiary.value,type:f.type.value,details:f.details.value,date:new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),status:'Delivered'});saveData(d);f.reset();toast('Assistance record added successfully.');renderAssistance();renderDashboard()}
function fillShelters(){const d=getData();document.querySelectorAll('select[name="shelter"]').forEach(s=>s.innerHTML=d.shelters.map(x=>`<option>${esc(x.name)}</option>`).join(''))}
function renderDashboard(){const d=getData(),vals=[d.shelters.length,d.families.length,d.shelters.reduce((a,x)=>a+Math.max(0,x.capacity-x.occupancy),0),d.assistance.length];['totalShelters','totalFamilies','availableCapacity','assistanceRequests'].forEach((id,i)=>{const e=document.getElementById(id);if(e)e.textContent=vals[i].toLocaleString()});const cap=d.shelters.reduce((a,x)=>a+x.capacity,0),occ=d.shelters.reduce((a,x)=>a+x.occupancy,0),rate=cap?Math.round(occ/cap*100):0;const r=document.getElementById('occupancyRate'),b=document.getElementById('occBar');if(r)r.textContent=rate+'%';if(b)b.style.width=Math.min(rate,100)+'%';const rows=document.getElementById('recentRows');if(rows)rows.innerHTML=d.assistance.slice(0,5).map(x=>`<tr><td>${esc(x.beneficiary)}</td><td>${esc(x.type)}</td><td>${esc(x.date)}</td><td><span class="status">${esc(x.status)}</span></td></tr>`).join('')||'<tr><td colspan="4" class="empty">No records yet.</td></tr>'}
function renderShelters(){const d=getData(),q=(document.getElementById('search')?.value||'').toLowerCase(),rows=d.shelters.filter(x=>(x.name+x.location).toLowerCase().includes(q)),el=document.getElementById('shelterRows');if(!el)return;el.innerHTML=rows.length?rows.map(x=>{const p=x.capacity?Math.round(x.occupancy/x.capacity*100):0,c=p>=95?'danger':p>=80?'warning':'';return `<tr><td>${esc(x.name)}</td><td>${esc(x.location)}</td><td>${x.capacity}</td><td>${x.occupancy}</td><td><span class="status ${c}">${p>=95?'Full':p>=80?'Limited':'Available'}</span></td><td><button class="small-btn danger-btn" onclick="deleteShelter(${x.id})">Delete</button></td></tr>`}).join(''):'<tr><td colspan="6" class="empty">No shelters found.</td></tr>'}
function renderFamilies(){const d=getData(),q=(document.getElementById('search')?.value||'').toLowerCase(),rows=d.families.filter(x=>(x.head+x.shelter+x.needs).toLowerCase().includes(q)),el=document.getElementById('familyRows');if(!el)return;el.innerHTML=rows.length?rows.map(x=>`<tr><td>${esc(x.head)}</td><td>${x.members}</td><td>${esc(x.shelter)}</td><td>${esc(x.needs||'—')}</td><td><button class="small-btn danger-btn" onclick="deleteFamily(${x.id})">Delete</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">No families found.</td></tr>'}
function renderAssistance(){const d=getData(),q=(document.getElementById('search')?.value||'').toLowerCase(),rows=d.assistance.filter(x=>(x.beneficiary+x.type+x.details).toLowerCase().includes(q)),el=document.getElementById('assistanceRows');if(!el)return;el.innerHTML=rows.length?rows.map(x=>`<tr><td>${esc(x.beneficiary)}</td><td>${esc(x.type)}</td><td>${esc(x.details)}</td><td>${esc(x.date)}</td><td><span class="status">${esc(x.status)}</span></td></tr>`).join(''):'<tr><td colspan="5" class="empty">No assistance records found.</td></tr>'}
function resetDemo(){if(confirm('Reset prototype data?')){localStorage.setItem(KEY,JSON.stringify(DEFAULT));location.reload()}}
document.addEventListener('DOMContentLoaded',()=>{if(document.body.dataset.app)guard();renderDashboard();renderShelters();renderFamilies();renderAssistance();fillShelters()});
